[staging]
staging-server ansible_host=192.168.1.100 ansible_user=ubuntu

[production]
prod-server-01 ansible_host=192.168.1.200 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
cirt_app_dir=/opt/cirt
cirt_port=9090
cirt_db_port=5432
